version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mrdinner}
      POSTGRES_USER: ${POSTGRES_USER:-mrdinner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mrdinner}
      TZ: Asia/Seoul
      PGTZ: Asia/Seoul
    ports: ["5432:5432"] ## no exposed db port on production
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    env_file: ../.env
    depends_on:
      - db
    ports: ["8000:8000"]
    volumes:
      - ../:/app
    entrypoint: ["/bin/bash", "./docker/web/entrypoint.sh"]

volumes:
  pgdata:
